{
  imports = [
    #./aerial.nix
    ./theme
    ./alpha.nix
    ./bbye.nix
    ./colorizer.nix
    ./fidget.nix
    ./gitsigns.nix
    ./highlight-yank.nix
    ./illuminate.nix
    ./indent-blankline.nix
    ./lastplace.nix
    ./lazygit.nix
    ./noice.nix
    ./notify.nix
    ./precognition.nix
    ./rainbow-delimiters.nix
    ./toggleterm.nix
    ./undotree.nix
    ./which-key.nix
    ./wilder.nix
  ];
}
